# Generated by Django 5.2.9 on 2026-01-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='имя'),
        ),
    ]
